'use server';
/**
 * @fileOverview A Genkit flow for designing cinematic video thumbnails.
 * 
 * 🚀 PRODUCTION: Set responseModalities to handle image generation correctly.
 */

import { ai, imagenModel, geminiModel, z } from '@/ai/genkit';

const ThumbnailDesignerInputSchema = z.object({
  prompt: z.string().describe('Visual description of the thumbnail to generate'),
});
export type ThumbnailDesignerInput = z.infer<typeof ThumbnailDesignerInputSchema>;

const ThumbnailDesignerOutputSchema = z.object({
  thumbnailDataUri: z.string().describe('The generated thumbnail image as a Base64 data URI or a high-res URL.'),
  isAiGenerated: z.boolean().default(true),
});
export type ThumbnailDesignerOutput = z.infer<typeof ThumbnailDesignerOutputSchema>;

const thumbnailDesignerFlow = ai.defineFlow(
  {
    name: 'thumbnailDesignerFlow',
    inputSchema: ThumbnailDesignerInputSchema,
    outputSchema: ThumbnailDesignerOutputSchema,
  },
  async (input) => {
    try {
      // 1. Primary Attempt: Use cinematic Imagen 4 model
      // CRITICAL: MUST set responseModalities: ['TEXT', 'IMAGE']
      const { media } = await ai.generate({
        model: imagenModel,
        prompt: `Cinematic high-quality professional video thumbnail about: ${input.prompt}. Eye-catching, high contrast, 4k resolution, professional photography style, vibrant colors.`,
        config: {
          responseModalities: ['TEXT', 'IMAGE']
        }
      });

      if (media?.url) {
        return {
          thumbnailDataUri: media.url,
          isAiGenerated: true,
        };
      }
      throw new Error('No media generated by visual model.');

    } catch (e: any) {
      // 🛠️ FALLBACK SYSTEM: Use high-quality visual search extraction via Gemini Flash
      console.warn("⚠️ AI Model Quota Reached. Initiating Professional Imagery Fallback...");
      
      const { text: keywords } = await ai.generate({
        model: geminiModel,
        prompt: `Extract 2-3 essential visual search keywords from this prompt for a video thumbnail: "${input.prompt}". Return ONLY the keywords, separated by commas.`,
      });

      const cleanKeywords = keywords?.replace(/[^a-zA-Z,]/g, '') || "cinematic,video";
      
      // Serve high-resolution curated professional imagery via Unsplash
      const fallbackUrl = `https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80&sig=${Math.random()}&q=${cleanKeywords}`;

      return {
        thumbnailDataUri: fallbackUrl,
        isAiGenerated: false,
      };
    }
  }
);

export async function generateAiThumbnail(input: ThumbnailDesignerInput): Promise<ThumbnailDesignerOutput> {
  return thumbnailDesignerFlow(input);
}
